wandb_version: 1

n_epochs:
  desc: null
  value: 10
dataset_type:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 0.0003
n_critics:
  desc: null
  value: 2
train_ratio:
  desc: null
  value: 0.2
test_ratio:
  desc: null
  value: 0.2
escnn:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695897449.201218
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 50
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.0
      5: 0.15.0
      8:
      - 5
